/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as PlatformToolsPlatformSettingsIndexRouteImport } from './routes/PlatformTools/platformSettings/index'
import { Route as PlatformToolsIntergrationIndexRouteImport } from './routes/PlatformTools/intergration/index'
import { Route as PlatformToolsDashboardIndexRouteImport } from './routes/PlatformTools/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformToolsPlatformSettingsIndexRoute =
  PlatformToolsPlatformSettingsIndexRouteImport.update({
    id: '/PlatformTools/platformSettings/',
    path: '/PlatformTools/platformSettings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsIntergrationIndexRoute =
  PlatformToolsIntergrationIndexRouteImport.update({
    id: '/PlatformTools/intergration/',
    path: '/PlatformTools/intergration/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsDashboardIndexRoute =
  PlatformToolsDashboardIndexRouteImport.update({
    id: '/PlatformTools/dashboard/',
    path: '/PlatformTools/dashboard/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/contact': typeof ContactIndexRoute
  '/PlatformTools/dashboard': typeof PlatformToolsDashboardIndexRoute
  '/PlatformTools/intergration': typeof PlatformToolsIntergrationIndexRoute
  '/PlatformTools/platformSettings': typeof PlatformToolsPlatformSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/contact': typeof ContactIndexRoute
  '/PlatformTools/dashboard': typeof PlatformToolsDashboardIndexRoute
  '/PlatformTools/intergration': typeof PlatformToolsIntergrationIndexRoute
  '/PlatformTools/platformSettings': typeof PlatformToolsPlatformSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/contact/': typeof ContactIndexRoute
  '/PlatformTools/dashboard/': typeof PlatformToolsDashboardIndexRoute
  '/PlatformTools/intergration/': typeof PlatformToolsIntergrationIndexRoute
  '/PlatformTools/platformSettings/': typeof PlatformToolsPlatformSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/sign-in'
    | '/contact'
    | '/PlatformTools/dashboard'
    | '/PlatformTools/intergration'
    | '/PlatformTools/platformSettings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/sign-in'
    | '/contact'
    | '/PlatformTools/dashboard'
    | '/PlatformTools/intergration'
    | '/PlatformTools/platformSettings'
  id:
    | '__root__'
    | '/'
    | '/(auth)/register'
    | '/(auth)/sign-in'
    | '/contact/'
    | '/PlatformTools/dashboard/'
    | '/PlatformTools/intergration/'
    | '/PlatformTools/platformSettings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRegisterRoute: typeof authRegisterRoute
  authSignInRoute: typeof authSignInRoute
  ContactIndexRoute: typeof ContactIndexRoute
  PlatformToolsDashboardIndexRoute: typeof PlatformToolsDashboardIndexRoute
  PlatformToolsIntergrationIndexRoute: typeof PlatformToolsIntergrationIndexRoute
  PlatformToolsPlatformSettingsIndexRoute: typeof PlatformToolsPlatformSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/platformSettings/': {
      id: '/PlatformTools/platformSettings/'
      path: '/PlatformTools/platformSettings'
      fullPath: '/PlatformTools/platformSettings'
      preLoaderRoute: typeof PlatformToolsPlatformSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/intergration/': {
      id: '/PlatformTools/intergration/'
      path: '/PlatformTools/intergration'
      fullPath: '/PlatformTools/intergration'
      preLoaderRoute: typeof PlatformToolsIntergrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/dashboard/': {
      id: '/PlatformTools/dashboard/'
      path: '/PlatformTools/dashboard'
      fullPath: '/PlatformTools/dashboard'
      preLoaderRoute: typeof PlatformToolsDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRegisterRoute: authRegisterRoute,
  authSignInRoute: authSignInRoute,
  ContactIndexRoute: ContactIndexRoute,
  PlatformToolsDashboardIndexRoute: PlatformToolsDashboardIndexRoute,
  PlatformToolsIntergrationIndexRoute: PlatformToolsIntergrationIndexRoute,
  PlatformToolsPlatformSettingsIndexRoute:
    PlatformToolsPlatformSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
