/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in/index.tsx'
import { Route as authRegisterRouteImport } from './routes/(auth)/sign-in/index.tsx'
import { Route as PlatformToolsPlatformSettingsIndexRouteImport } from './routes/PlatformTools/platformSettings/index'
import { Route as PlatformToolsIntergrationIndexRouteImport } from './routes/PlatformTools/intergration/index'
import { Route as PlatformToolsDashboardIndexRouteImport } from './routes/PlatformTools/dashboard/index'
import { Route as PlatformToolsSignatureLibraryIndexRouteImport } from './routes/PlatformTools/SignatureLibrary/index'
import { Route as PlatformToolsSignatureGeneratorIndexRouteImport } from './routes/PlatformTools/SignatureGenerator/index'
import { Route as PlatformToolsSignatureLibrarySignatureIDIndexRouteImport } from './routes/PlatformTools/SignatureLibrary/$SignatureID/index'
import { Route as PlatformToolsSignatureGeneratorEditorIndexRouteImport } from './routes/PlatformTools/SignatureGenerator/Editor/index'
import { Route as PlatformToolsSignatureLibrarySignatureIDEditorIndexRouteImport } from './routes/PlatformTools/SignatureLibrary/$SignatureID/Editor/index'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformToolsPlatformSettingsIndexRoute =
  PlatformToolsPlatformSettingsIndexRouteImport.update({
    id: '/PlatformTools/platformSettings/',
    path: '/PlatformTools/platformSettings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsIntergrationIndexRoute =
  PlatformToolsIntergrationIndexRouteImport.update({
    id: '/PlatformTools/intergration/',
    path: '/PlatformTools/intergration/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsDashboardIndexRoute =
  PlatformToolsDashboardIndexRouteImport.update({
    id: '/PlatformTools/dashboard/',
    path: '/PlatformTools/dashboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsSignatureLibraryIndexRoute =
  PlatformToolsSignatureLibraryIndexRouteImport.update({
    id: '/PlatformTools/SignatureLibrary/',
    path: '/PlatformTools/SignatureLibrary/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsSignatureGeneratorIndexRoute =
  PlatformToolsSignatureGeneratorIndexRouteImport.update({
    id: '/PlatformTools/SignatureGenerator/',
    path: '/PlatformTools/SignatureGenerator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsSignatureLibrarySignatureIDIndexRoute =
  PlatformToolsSignatureLibrarySignatureIDIndexRouteImport.update({
    id: '/PlatformTools/SignatureLibrary/$SignatureID/',
    path: '/PlatformTools/SignatureLibrary/$SignatureID/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsSignatureGeneratorEditorIndexRoute =
  PlatformToolsSignatureGeneratorEditorIndexRouteImport.update({
    id: '/PlatformTools/SignatureGenerator/Editor/',
    path: '/PlatformTools/SignatureGenerator/Editor/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute =
  PlatformToolsSignatureLibrarySignatureIDEditorIndexRouteImport.update({
    id: '/PlatformTools/SignatureLibrary/$SignatureID/Editor/',
    path: '/PlatformTools/SignatureLibrary/$SignatureID/Editor/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/contact': typeof ContactIndexRoute
  '/PlatformTools/SignatureGenerator': typeof PlatformToolsSignatureGeneratorIndexRoute
  '/PlatformTools/SignatureLibrary': typeof PlatformToolsSignatureLibraryIndexRoute
  '/PlatformTools/dashboard': typeof PlatformToolsDashboardIndexRoute
  '/PlatformTools/intergration': typeof PlatformToolsIntergrationIndexRoute
  '/PlatformTools/platformSettings': typeof PlatformToolsPlatformSettingsIndexRoute
  '/PlatformTools/SignatureGenerator/Editor': typeof PlatformToolsSignatureGeneratorEditorIndexRoute
  '/PlatformTools/SignatureLibrary/$SignatureID': typeof PlatformToolsSignatureLibrarySignatureIDIndexRoute
  '/PlatformTools/SignatureLibrary/$SignatureID/Editor': typeof PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/contact': typeof ContactIndexRoute
  '/PlatformTools/SignatureGenerator': typeof PlatformToolsSignatureGeneratorIndexRoute
  '/PlatformTools/SignatureLibrary': typeof PlatformToolsSignatureLibraryIndexRoute
  '/PlatformTools/dashboard': typeof PlatformToolsDashboardIndexRoute
  '/PlatformTools/intergration': typeof PlatformToolsIntergrationIndexRoute
  '/PlatformTools/platformSettings': typeof PlatformToolsPlatformSettingsIndexRoute
  '/PlatformTools/SignatureGenerator/Editor': typeof PlatformToolsSignatureGeneratorEditorIndexRoute
  '/PlatformTools/SignatureLibrary/$SignatureID': typeof PlatformToolsSignatureLibrarySignatureIDIndexRoute
  '/PlatformTools/SignatureLibrary/$SignatureID/Editor': typeof PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/contact/': typeof ContactIndexRoute
  '/PlatformTools/SignatureGenerator/': typeof PlatformToolsSignatureGeneratorIndexRoute
  '/PlatformTools/SignatureLibrary/': typeof PlatformToolsSignatureLibraryIndexRoute
  '/PlatformTools/dashboard/': typeof PlatformToolsDashboardIndexRoute
  '/PlatformTools/intergration/': typeof PlatformToolsIntergrationIndexRoute
  '/PlatformTools/platformSettings/': typeof PlatformToolsPlatformSettingsIndexRoute
  '/PlatformTools/SignatureGenerator/Editor/': typeof PlatformToolsSignatureGeneratorEditorIndexRoute
  '/PlatformTools/SignatureLibrary/$SignatureID/': typeof PlatformToolsSignatureLibrarySignatureIDIndexRoute
  '/PlatformTools/SignatureLibrary/$SignatureID/Editor/': typeof PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sso-callback'
    | '/register'
    | '/sign-in'
    | '/contact'
    | '/PlatformTools/SignatureGenerator'
    | '/PlatformTools/SignatureLibrary'
    | '/PlatformTools/dashboard'
    | '/PlatformTools/intergration'
    | '/PlatformTools/platformSettings'
    | '/PlatformTools/SignatureGenerator/Editor'
    | '/PlatformTools/SignatureLibrary/$SignatureID'
    | '/PlatformTools/SignatureLibrary/$SignatureID/Editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sso-callback'
    | '/register'
    | '/sign-in'
    | '/contact'
    | '/PlatformTools/SignatureGenerator'
    | '/PlatformTools/SignatureLibrary'
    | '/PlatformTools/dashboard'
    | '/PlatformTools/intergration'
    | '/PlatformTools/platformSettings'
    | '/PlatformTools/SignatureGenerator/Editor'
    | '/PlatformTools/SignatureLibrary/$SignatureID'
    | '/PlatformTools/SignatureLibrary/$SignatureID/Editor'
  id:
    | '__root__'
    | '/'
    | '/sso-callback'
    | '/(auth)/register'
    | '/(auth)/sign-in'
    | '/contact/'
    | '/PlatformTools/SignatureGenerator/'
    | '/PlatformTools/SignatureLibrary/'
    | '/PlatformTools/dashboard/'
    | '/PlatformTools/intergration/'
    | '/PlatformTools/platformSettings/'
    | '/PlatformTools/SignatureGenerator/Editor/'
    | '/PlatformTools/SignatureLibrary/$SignatureID/'
    | '/PlatformTools/SignatureLibrary/$SignatureID/Editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  authRegisterRoute: typeof authRegisterRoute
  authSignInRoute: typeof authSignInRoute
  ContactIndexRoute: typeof ContactIndexRoute
  PlatformToolsSignatureGeneratorIndexRoute: typeof PlatformToolsSignatureGeneratorIndexRoute
  PlatformToolsSignatureLibraryIndexRoute: typeof PlatformToolsSignatureLibraryIndexRoute
  PlatformToolsDashboardIndexRoute: typeof PlatformToolsDashboardIndexRoute
  PlatformToolsIntergrationIndexRoute: typeof PlatformToolsIntergrationIndexRoute
  PlatformToolsPlatformSettingsIndexRoute: typeof PlatformToolsPlatformSettingsIndexRoute
  PlatformToolsSignatureGeneratorEditorIndexRoute: typeof PlatformToolsSignatureGeneratorEditorIndexRoute
  PlatformToolsSignatureLibrarySignatureIDIndexRoute: typeof PlatformToolsSignatureLibrarySignatureIDIndexRoute
  PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute: typeof PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/platformSettings/': {
      id: '/PlatformTools/platformSettings/'
      path: '/PlatformTools/platformSettings'
      fullPath: '/PlatformTools/platformSettings'
      preLoaderRoute: typeof PlatformToolsPlatformSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/intergration/': {
      id: '/PlatformTools/intergration/'
      path: '/PlatformTools/intergration'
      fullPath: '/PlatformTools/intergration'
      preLoaderRoute: typeof PlatformToolsIntergrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/dashboard/': {
      id: '/PlatformTools/dashboard/'
      path: '/PlatformTools/dashboard'
      fullPath: '/PlatformTools/dashboard'
      preLoaderRoute: typeof PlatformToolsDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/SignatureLibrary/': {
      id: '/PlatformTools/SignatureLibrary/'
      path: '/PlatformTools/SignatureLibrary'
      fullPath: '/PlatformTools/SignatureLibrary'
      preLoaderRoute: typeof PlatformToolsSignatureLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/SignatureGenerator/': {
      id: '/PlatformTools/SignatureGenerator/'
      path: '/PlatformTools/SignatureGenerator'
      fullPath: '/PlatformTools/SignatureGenerator'
      preLoaderRoute: typeof PlatformToolsSignatureGeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/SignatureLibrary/$SignatureID/': {
      id: '/PlatformTools/SignatureLibrary/$SignatureID/'
      path: '/PlatformTools/SignatureLibrary/$SignatureID'
      fullPath: '/PlatformTools/SignatureLibrary/$SignatureID'
      preLoaderRoute: typeof PlatformToolsSignatureLibrarySignatureIDIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/SignatureGenerator/Editor/': {
      id: '/PlatformTools/SignatureGenerator/Editor/'
      path: '/PlatformTools/SignatureGenerator/Editor'
      fullPath: '/PlatformTools/SignatureGenerator/Editor'
      preLoaderRoute: typeof PlatformToolsSignatureGeneratorEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PlatformTools/SignatureLibrary/$SignatureID/Editor/': {
      id: '/PlatformTools/SignatureLibrary/$SignatureID/Editor/'
      path: '/PlatformTools/SignatureLibrary/$SignatureID/Editor'
      fullPath: '/PlatformTools/SignatureLibrary/$SignatureID/Editor'
      preLoaderRoute: typeof PlatformToolsSignatureLibrarySignatureIDEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  authRegisterRoute: authRegisterRoute,
  authSignInRoute: authSignInRoute,
  ContactIndexRoute: ContactIndexRoute,
  PlatformToolsSignatureGeneratorIndexRoute:
    PlatformToolsSignatureGeneratorIndexRoute,
  PlatformToolsSignatureLibraryIndexRoute:
    PlatformToolsSignatureLibraryIndexRoute,
  PlatformToolsDashboardIndexRoute: PlatformToolsDashboardIndexRoute,
  PlatformToolsIntergrationIndexRoute: PlatformToolsIntergrationIndexRoute,
  PlatformToolsPlatformSettingsIndexRoute:
    PlatformToolsPlatformSettingsIndexRoute,
  PlatformToolsSignatureGeneratorEditorIndexRoute:
    PlatformToolsSignatureGeneratorEditorIndexRoute,
  PlatformToolsSignatureLibrarySignatureIDIndexRoute:
    PlatformToolsSignatureLibrarySignatureIDIndexRoute,
  PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute:
    PlatformToolsSignatureLibrarySignatureIDEditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
